wordpress_ip: "{{ aws_instance_sample__public_ip }}"
wordpress_db_host: "{{ aws_db_instance_sample__address }}"
wordpress_db: "{{ aws_db_instance_sample__name }}"
wordpress_db_user: "{{ aws_db_instance_sample__username }}"
wordpress_db_password: "{{ aws_db_instance_sample__password }}"
